Joint Testing 3 - Agentic Testing (#7)
* update requirements

* updated repo endpoints

* updated repo endpoints

* updated tools file

* joint testing

* added draft of agentic runner module

* updated dataset py to accept agents

* changed some stuff

* added dataset and tools to support agents for now

* added working draft for agentic testing

* Search tools - Updated

Replaced DuckDuckGo and other web searches to Google Search.

* Removed duplicate files

* Tools udpated for JT3

Updated tools according to the dataset and created few files for the dataset.

* Update tools.py

Added tools for ia-leakage

* Removed the unused files(tools related)

Updated the tools with ASB tool set.

* Update .gitignore

Add moonshot folders to .gitignore

* Add tools for jt3-leakage-te dataset

* intermediate move to mcp

* impl mcp

* Update tools for ASB dataset

* updated tools

* Update emails tools

* merged with updated react agent

* Update emails tools

* moved tools

* Removed moonshot-data-aisi from repository

* Update sast-codeql.yaml

* allowed tooling to be added in recipe

* added fraud v2

* integrate jointTesting 3 data

* Update requirements.txt

Update requirements.txt

* Delete moonshot-data-aisi

* Update dataset_arguments.py

Fix bug

* update recipe args

Update recipe args for update_recipe and add_recipe to handle tools field.

* Updated recipe.py

Updated the tools argument as optional and none empty string if being used

* Updated Cookbook

Updated Cookbook.py to handle to tools for view_cookbook cli function

* Update api_recipe.py

* Update README.md

* Fix add_recipe and tests

* removed unused agents field in dataset arguments

* updated unit tests for new functionality

* Update requirements.txt

* Update requirements.txt

* updated with unit tests

added the functionality to handle edge cases for tools in recipes

* Update smoke-test-cli.yaml

* updated test_recipes to include more test cases

* Fix linting issues

* Update pre-build-checks.yaml

Add pytest-asyncio to dependencies

* Fix linting errors and update smoke test

* Workflow cleanup

Differentiate weak and strong copyleft licenses

* Workflow cleanup

* Update dependencies

* Update dependencies

* Update versions

* Update README.md

* Change clone branch to main

- updated starlette to 0.47.2
- updated fastapi to 0.116.1

* Change data branch to dev_main

---------

Co-authored-by: Lionel Teo <93119265+imda-lionelteo@users.noreply.github.com>
Co-authored-by: imda-jacksonboey <jackson_boey@imda.gov.sg>
Co-authored-by: Nigel <nigel@example.com>
Co-authored-by: naganikshith04 <naga.ng@ntu.edu.sg>
Co-authored-by: GabrielWLM-SGAISI <gabrielwl.matienzo@ntu.edu.sg>
Co-authored-by: nigel <nigel>

diff --git a/.github/workflows/sast-codeql.yaml b/.github/workflows/sast-codeql.yaml
--- a/.github/workflows/sast-codeql.yaml
+++ b/.github/workflows/sast-codeql.yaml
@@ -1,38 +1,29 @@
-# For most projects, this workflow file will not need changing; you simply need
-# to commit it to your repository.
-#
-# You may wish to alter this file to override the set of languages analyzed,
-# or to provide custom queries or build logic.
-#
-# ******** NOTE ********
-# We have attempted to detect the languages in your repository. Please check
-# the `language` matrix defined below to confirm you have the correct set of
-# supported CodeQL languages.
-#
+
 name: "SAST - CodeQL"
 
 on:
+  # Run when code is pushed to the main branch
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "dev_main", "main" ]
-#  # Trigger every Friday at 10:05pm (14:05 UTC)
-#  # cron: min hr day-of-mth mth day-of-week
-#  schedule:
-#    - cron: "5 14 * * 5"
+    branches: [ main ]
 
+  # Run when pull requests are created against dev_main
+  pull_request:
+    branches: [ dev_main ]
+
+  # Allow manual triggering with a branch parameter
   workflow_dispatch:
     inputs:
       branch_to_test:
-        description: 'Branch or tag to run test'
+        description: 'Branch or tag to run scan'
         required: true
         default: 'dev_main'
         type: string
 
+  # Allow other workflows to call this workflow with parameters
   workflow_call:
     inputs:
       branch_to_test:
-        description: 'Branch or tag to run test'
+        description: 'Branch or tag to run scan'
         required: true
         default: 'dev_main'
         type: string
@@ -40,30 +31,27 @@ on:
 jobs:
   analyze:
     name: Analyze (${{ matrix.language }})
-    # Runner size impacts CodeQL analysis time. To learn more, please see:
-    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
-    #   - https://gh.io/supported-runners-and-hardware-resources
-    #   - https://gh.io/using-larger-runners (GitHub.com only)
-    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
     runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
     timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
     permissions:
-      # required for all workflows
+      # Access to upload code scanning results
       security-events: write
-
-      # required to fetch internal or private CodeQL packs
+      # Access to fetch CodeQL packs
       packages: read
-
-      # only required for workflows in private repositories
+      # Permissions needed for private repositories
       actions: read
       contents: read
 
+    # Define strategy for matrix jobs
     strategy:
+      # Continue with other jobs even if one fails
       fail-fast: false
       matrix:
+        # Define languages to analyze
         include:
         - language: python
           build-mode: none
+        # Documentation for other supported languages and options
         # CodeQL supports the following values keywords for 'language': 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
         # Use `c-cpp` to analyze code written in C, C++ or both
         # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
@@ -72,107 +60,62 @@ jobs:
         # see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
         # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how
         # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
+    
     steps:
 
-    - name: Set branch variable (pull_request)
-      if: github.event_name == 'pull_request'
-      run: |
-        echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> "$GITHUB_ENV"
-        echo "PR_NUM=#${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"
+      # Set branch variable based on the event that triggered the workflow
+      - name: Set branch variable
+        run: |
+          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
+            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+            echo "PR_NUM=#${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
+            echo "BRANCH=${{ inputs.branch_to_test }}" >> $GITHUB_ENV
+            echo "PR_NUM=#0" >> $GITHUB_ENV
+          elif [[ ${{ github.event_name }} == 'push' ]]; then
+            echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
+            echo "PR_NUM=#0" >> $GITHUB_ENV
+          elif [[ ${{ github.event_name }} == 'workflow_call' ]]; then
+            echo "BRANCH=${{ inputs.branch_to_test }}" >> $GITHUB_ENV
+            echo "PR_NUM=#0" >> $GITHUB_ENV
+          else
+            echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
+            echo "PR_NUM=#0" >> $GITHUB_ENV
+          fi
 
-    - name: Set branch variable (workflow_dispatch)
-      if: github.event_name == 'workflow_dispatch'
-      run: |
-        echo "BRANCH=${{ inputs.branch_to_test }}" >> "$GITHUB_ENV"
-        echo "PR_NUM=#0" >> "$GITHUB_ENV"
+      # Checkout the repository code to analyze
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ env.BRANCH }}
+          submodules: recursive
 
-    - name: Checkout Code
-      uses: actions/checkout@v4
-      with:
-        ref: ${{ env.BRANCH }}
-        submodules: recursive
+      # Set up the CodeQL tools and database
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: ${{ matrix.language }}
+          build-mode: ${{ matrix.build-mode }}
+          # Configuration options for custom queries (commented)
+          # queries: security-extended,security-and-quality
 
-    # Initializes the CodeQL tools for scanning.
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        build-mode: ${{ matrix.build-mode }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
+      # Run the CodeQL analysis
+      - name: Perform CodeQL Analysis
+        id: codeql_analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+          category: "/language:${{matrix.language}}"
 
-        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
-
-    # If the analyze step fails for one of the languages you are analyzing with
-    # "We were unable to automatically build your code", modify the matrix above
-    # to set the build mode to "manual" for that language. Then modify this step
-    # to build your code.
-    # ℹ️ Command-line programs to run using the OS shell.
-    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    - if: matrix.build-mode == 'manual'
-      shell: bash
-      run: |
-        echo 'If you are using a "manual" build mode for one or more of the' \
-          'languages you are analyzing, replace this with the commands to build' \
-          'your code, for example:'
-        echo '  make bootstrap'
-        echo '  make release'
-        exit 1
-
-    - name: Perform CodeQL Analysis
-      id: codeql_analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
-
-    - name: Generate CodeQL Analysis Summary
-      id: codeql_summary
-      if: ${{ ! cancelled() }}
-      run: |
-        set +e
-        source ci/run-codeql-summ.sh
-        exit_code=$?
-        set -e        
-        echo "CODEQL_SUMMARY=$CODEQL_SUMMARY" >> $GITHUB_ENV
-        exit $exit_code
-      env:
-        GH_TOKEN: ${{ github.token }}
-
-    - name: Add comment to PR
-      if: ${{ ! cancelled() }}
-      run: |
-        COMMENT="CodeQL Analysis Complete: \
-          \nStatus: SAST: ${{ steps.codeql_summary.outcome }} \
-          \nDetails: ${{ env.CODEQL_SUMMARY }} \
-          \nReference: ${{ github.server_url }}/${{ github.repository }}/security/code-scanning"
-
-        curl -L \
-          -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer $GH_TOKEN" \
-          https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUM }}/commits \
-          -d '{"body": "'"$COMMENT"'"}'
-
-        if [[ $? -ne 0 ]]; then
-          echo "Error posting comment"
-          exit 1
-        fi
-      env:
-        GH_TOKEN: ${{ github.token }}
-
-    # # Send slack notification
-    # - name: Send slack notification
-    #   if: ${{ ! cancelled() }}
-    #   uses: slackapi/slack-github-action@v1.26.0
-    #   with:
-    #     payload: |
-    #       {
-    #         "workflow": "${{ github.repository }} - ${{ github.workflow }} - ${{ env.PR_NUM }}",
-    #         "status": "SAST: ${{ steps.codeql_summary.outcome }}",
-    #         "details": "${{ env.CODEQL_SUMMARY }}",
-    #         "ref": "${{ github.server_url }}/${{ github.repository }}/security/code-scanning"
-    #       }
-    #   env:
-    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      # Generate a summary of the analysis results
+      - name: Generate CodeQL Analysis Summary
+        id: codeql_summary
+        if: ${{ ! cancelled() }}
+        run: |
+          set +e
+          source ci/run-codeql-summ.sh
+          exit_code=$?
+          set -e        
+          echo "CODEQL_SUMMARY=$CODEQL_SUMMARY" >> $GITHUB_ENV
+          exit $exit_code
+        env:
+          GH_TOKEN: ${{ github.token }}
