Update comment to PR step

diff --git a/.github/workflows/sast-codeql.yaml b/.github/workflows/sast-codeql.yaml
--- a/.github/workflows/sast-codeql.yaml
+++ b/.github/workflows/sast-codeql.yaml
@@ -15,7 +15,7 @@ on:
   push:
     branches: [ "main" ]
   pull_request:
-    branches: [ "dev_main" ]
+    branches: [ "dev_main", "main" ]
 #  # Trigger every Friday at 10:05pm (14:05 UTC)
 #  # cron: min hr day-of-mth mth day-of-week
 #  schedule:
@@ -140,25 +140,27 @@ jobs:
       env:
         GH_TOKEN: ${{ github.token }}
 
-    # - name: Add comment to PR
-    #   if: ${{ ! cancelled() }}
-    #   run: |
-    #     COMMENT: |
-    #       CodeQL Analysis Complete: 
-    #       Status: SAST: ${{ steps.codeql_summary.outcome }}
-    #       Details: ${{ env.CODEQL_SUMMARY }}
-    #       Reference: ${{ github.server_url }}/${{ github.repository }}/security/code-scanning
+    - name: Add comment to PR
+      if: ${{ ! cancelled() }}
+      run: |
+        COMMENT="CodeQL Analysis Complete: \
+          \nStatus: SAST: ${{ steps.codeql_summary.outcome }} \
+          \nDetails: ${{ env.CODEQL_SUMMARY }} \
+          \nReference: ${{ github.server_url }}/${{ github.repository }}/security/code-scanning"
 
-    #     RESPONSE=$(curl -X POST \
-    #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-    #       -H "Accept: application/vnd.github.v3+json" \
-    #       -d '{"body": "'"$COMMENT"'"}' \
-    #       "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/comments")
+        curl -L \
+          -X POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer $GH_TOKEN" \
+          https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUM }}/commits \
+          -d '{"body": "'"$COMMENT"'"}'
 
-    #     if [[ $? -ne 0 ]]; then
-    #       echo "Error posting comment: $RESPONSE"
-    #       exit 1
-    #     fi
+        if [[ $? -ne 0 ]]; then
+          echo "Error posting comment"
+          exit 1
+        fi
+      env:
+        GH_TOKEN: ${{ github.token }}
 
     # # Send slack notification
     # - name: Send slack notification
